slaclab/slac-alarm-manager

- slam/alarm_item.py
- slam/alarm_table_model.py
- slam/alarm_table_view.py
- slam/alarm_tree_model.py
- slam/alarm_tree_view.py
- slam/main_window.py
- slam/tests/test_alarm_item.py
Change severity from a string to an enum. Add a __repr__ method. Clean up unnecessary code. Add some tests.
> AlarmItem Cleanup

- slam/alarm_configuration_widget.py
- slam/tests/conftest.py
- slam/tests/test_alarm_configuration_widget.py
Some documentation and code cleanup for the `AlarmConfigurationWidget`. Adds associated unit tests.
> AlarmConfigurationWidget cleanup

- slam/alarm_item.py
- slam/alarm_table_model.py
- slam/alarm_tree_model.py
Cleanup the code for determining what color to draw alarms in.
> MAINT: Cleanup the color related code

- slam/alarm_table_model.py
- slam/alarm_tree_model.py
- slam/tests/conftest.py
- slam/tests/test_alarm_table_model.py
Also change color scheme for the table so it is only changing the severity text.
> MAINT/TST: Cleanup the alarm table model code, and add tests

- slam/alarm_table_view.py
- slam/tests/conftest.py
- slam/tests/test_alarm_table_view.py
Adding type hints, some styles fixes, and some code cleanup. Added tests.
> Cleanup alarm table view

- slam/alarm_tree_model.py
- slam/main_window.py
- slam/tests/test_alarm_tree_model.py
Some more code cleanup, doc fixes, and additional tests.
> Cleanup alarm tree model

- slam/alarm_tree_view.py
- slam/tests/test_alarm_table_view.py
- slam/tests/test_alarm_tree_view.py
Adds type hits, a tiny bit of cleanup, and more tests.
> Cleanup alarm tree view

- requirements.txt
- slam/alarm_item.py
- slam/alarm_table_model.py
- slam/alarm_tree_model.py
- slam/archive_search.py
- slam/kafka_reader.py
- slam/main_window.py
- slam_launcher/main.py
The plot code should move somewhere else eventually.
> Add logger, add requirements, cleanup some plot code

- .github/workflows/build-and-test.yml
- dev-requirements.txt
- examples/kafka_setup.py
Update the build/test workflow to use the new file.
> BLD: Add file for development requirements

- .github/workflows/build-and-test.yml
- README.md
- slam/alarm_tree_model.py
- slam/archive_search.py
- slam/main_window.py
- slam/tests/conftest.py
- slam/tests/test_alarm_item.py
> STY: Flake8 fixes

- slam/alarm_item.py
- slam/alarm_table_model.py
- slam/alarm_table_view.py
- slam/alarm_tree_model.py
- slam/tests/test_alarm_item.py
- slam/tests/test_alarm_table_model.py
Other enhancements and cleanup to follow, but need to move to something else first
> ENH: Add filtering capability to the alarm table

- slam/alarm_table_view.py
- slam/tests/test_alarm_table_view.py
Also includes re-ordering of columns.
> ENH: Multi-select for the table

- slam/alarm_table_view.py
- slam_launcher/main.py
Better initial size for the main window. Fix the alarm table filter layout.
> ENH: A couple minor UI improvements

- slam/alarm_table_view.py
- slam/alarm_tree_model.py
- slam/tests/test_alarm_table_view.py
- slam/tests/test_alarm_tree_model.py
Any action taken on the PV will be reflected in each other branch. So if a PV is part of 3 different paths, acknowledging it (or taking any other action) in one path will also apply to the other 2.
> ENH: Allow for the same PV to appear in multiple branches of the tree

- doc-requirements.txt
- docs/alarm_manager.md
- docs/developer.md
- docs/index.md
- docs/pydm.md
- mkdocs.yml
The basic structure of the documentation that will be hosted for this project. Builds with mkdocs.
> DOC: Initial documentation checkin

- setup.py
- slam/alarm_table_view.py
- slam/main_window.py
Fix a label and rename a menu option
> FIX: Minor cleanups

- setup.py
- slam/alarm_tree_view.py
Ensure they get added properly
> FIX: Display actions on context menus

- slam/alarm_tree_view.py
- slam/tests/test_alarm_configuration_widget.py
- slam/tests/test_alarm_tree_view.py
[Screencast from 07-18-2023 02:09:05 PM.webm](https://github.com/slaclab/slac-alarm-manager/assets/137955700/982afb88-a768-44f7-b68c-dd0be03494f6)
> ENH: add context menu item to view guidance

- slam/main_window.py
- slam_launcher/main.py
idea on how to fail in nice way when user enters bad cmd-line args or can't connect kafka
> Fail early in nicer way

- slam/alarm_item.py
- slam/alarm_tree_model.py
- slam/main_window.py
- slam/tests/test_alarm_tree_model.py
Fixes the way a couple of the tree operations were handled to improve the application performance so it isn't doing wasteful computations on every redraw.
> ENH: Improve startup performance of the application
