slam/kafka_reader.py, slam/main_window.py, slam/tests/test_main_window.py, slam_launcher/main.py
Adds an extra argument when starting up the application to point to the location of the bootstrap server(s) for kafka.
=> ENH: Make kafka bootstrap servers configurable

slam/alarm_tree_model.py, slam/tests/test_alarm_tree_model.py
The xml file for monitored alarms will not necessarily have the items in order, so instead of setting the root to the first item, set it to the item that has no parent node.
Also fix a small issue with the display of alarm severity in the tree.
=> Set the root of the tree based on no parent node

slam/alarm_item.py, slam/alarm_tree_view.py
If an alarm item has pydm displays associated with it, add an action to the context menu for launching them. Fixes some type hints as well.
=> ENH: Launch pydm displays from the alarm tree

pydm_alarm_plugin/README.md, pydm_alarm_plugin/alarm_plugin.py, setup.py, slam/tests/test_alarm_plugin.py
Hi all,
I wanted to draw some attention to this part of the alarm work I've been doing since it would affect PyDM if installed alongside it.
We are in the process of rolling out the new alarm system (NALMS) (https://slaclab.github.io/nalms/) which is based heavily on the phoebus alarm server. Phoebus sends out alarm updates using a kafka cluster, allowing clients to read/write to kafka instead of EPICS directly.
When building a screen like lclshome, the current way to get top level alarm summaries for the buttons is to create an alarm IOC, which is an IOC that has alarm summary PVs which are set to the highest severity of the PVs which make up each summary PV. See the second heading here: https://www.slac.stanford.edu/grp/lcls/controls/sysGroup/LCLS%20Alarms.htm
In a brand new …
=> ENH: Add a PyDM data plugin for receiving alarm data from NALMS

slam/alarm_tree_model.py, slam/main_window.py, slam/tests/test_alarm_tree_model.py
Deleted items were still sticking around and being displayed in the tree/table.
=> FIX: Ensure kafka messages that indicate removal of an item cause it to be removed from the tree/table

slam/alarm_table_view.py, slam/kafka_reader.py, slam/main_window.py, slam_launcher/main.py
-topics is now a comma separated list for what to listen to from kafka. Allows switching between the topics using a combo box in the ui. Fixes an issue where data loading into the table was too slow using a proxy model from the start.
=> ENH: Monitor multiple alarm topics from kafka at the same time

slam/alarm_table_view.py, slam/main_window.py, slam/tests/test_alarm_table_view.py, slam/tests/test_main_window.py, slam_launcher/main.py
Allows for better use of the splitter widget, and is just a better way of doing this in general.
=> MAINT: Refactor the way the alarm tables are created

slam/alarm_table_view.py, slam/alarm_tree_view.py, slam/tests/test_alarm_table_view.py, slam/tests/test_alarm_tree_view.py
Follow-up to #31 to send multiple updates to kafka when a PV which appears multiple times in the tree is updated. This will allow all clients which read from kafka to see all updates.
=> ENH: Send updates to kafka for each path the PV is part of

pydm_alarm_plugin/alarm_plugin.py, slam/tests/test_alarm_plugin.py
The plugin will now accept a list of topics to monitor and send updates to widgets about. Also will no longer display acknowledged alarms as active. But the downside is they don't display as anything out of the ordinary at all. This may change in the future.
=> ENH: Update pydm plugin to support multiple kafka topics

slam/alarm_item.py, slam/alarm_tree_view.py, slam/tests/test_alarm_item.py
When acknowledging or unacknowledging and alarm at a non-leaf node in the alarm tree, will now send that action to the command topic separate for every active alarm along the path instead of only at the top level item acted upon. This will ensure clients (like the PyDM plugin) will correctly receive the state of every alarm along the path.
Added test for new method.
=> FIX: Properly send the (un)/acknowledge command when done at a non-leaf node

pydm_alarm_plugin/alarm_plugin.py
PyDM connection viewer was showing a False connection status for anything using the nalms protocol. This fixes it, as well as errors when using designer.
=> FIX: Set connection status correctly when establishing new alarm connection

pydm_alarm_plugin/alarm_plugin.py
Missed this when adding support for multiple topics causing top level summaries to be ignored
=> FIX: Set kafka topic list correctly in the pydm plugin

slam/main_window.py, slam/tests/test_main_window.py
Adds a big red banner saying that the client cannot reach the alarm server when there are connections issues. Maintain connection status per monitored kafka topic. Add associated unit test.
=> ENH: Add warning label indicating disconnect between client and alarm server

slam/alarm_item.py, slam/alarm_tree_model.py, slam/alarm_tree_view.py, slam/tests/test_alarm_tree_model.py, slam/tests/test_alarm_tree_view.py
Create a new `filtered` property that is separate from the `enabled` one. Kafka `state` messages will affect this new one, `config` messages will continue to toggle the `enabled` status. Cleanup a bunch of unnecessary code duplication.
=> FIX: Get alarm filter to work properly

slam/alarm_configuration_widget.py, slam/alarm_table_view.py, slam/alarm_tree_view.py, slam/permissions.py, slam/tests/test_permissions.py, slam_launcher/main.py
Adds read-only, operator, and admin permissions to the application which determine what actions a user is allowed to take. Very simple implementation at this time as individual user accounts aren't supported for this, it is just set at startup. Mostly just to defend against accidental changes.
=> ENH: Add user permissions

slam/alarm_table_view.py, slam/main_window.py, slam/tests/test_alarm_table_view.py
When a new alarm configuration is created that removes some alarms which are currently in an alarm state, they stick around in the state topic in kafka. This will send a delete message to kafka to ensure they are cleaned up.
=> FIX: Remove non-existent alarm paths from table when an action is taken

slam/alarm_table_model.py, slam/alarm_table_view.py
Use layoutChanged signal to prevent issue with the model index being invalid when a filter is applied. Map the proxy index to the source index when a user takes an action with a filter active.
=> FIX: Prevent segfaults when filtering the alarm table

slam/alarm_table_model.py, slam/tests/test_alarm_table_model.py
change default column order to be PV, Latched Severity, Current Severity, Description, Time, Value, Latched Status, Current Status
=> Rearrange column order

docs/pydm.md
Users can listen to more than one topic at once, so `PYDM_KAFKA_ALARM_TOPIC` should be plural.
=> DOC: Fix incorrect environment variable name in documentation

slam/alarm_table_view.py, slam/alarm_tree_model.py, slam/alarm_tree_view.py, slam/main_window.py, slam/tests/test_main_window.py
When more than 1 topic specified, add option to topic drop-down for 'All' which displays all the alarms across all topics in one tree-view and set of tables.
to try feature:
on dev-rhel7 machine: 
-slam --topics LCLS,CRYO --bootstrap-servers 172.24.5.224:9094
-select 'All' from drop-down menu in top left of application window
-tree view and tables should display alarms from all specified topics, should be able to enable/disable/ack alarms as usual
=> Add 'All' topic option

slam/alarm_tree_model.py
Also fixes issue where disabled-nodes are placed
at bottom of list, now remains in sorted order.
=> BUG: make alarm nodes be sorted alphabetically

slam/alarm_item.py, slam/alarm_table_view.py, slam/alarm_tree_view.py, slam/main_window.py
*ignore typo in branch name (thresh**h**olds), not present in the code
to see in action:
-"slam --topics CRYO --bootstrap-servers 172.24.8.133:9094" on dev-rhl7
-in tree menu, Global->Distribution->WATR:BSYA: 100:COMP_AIR_P, right-click and "Display Thresholds", should see values for the 4 thresholds. 
-can right-click on other alarm-items in tree and should see "None" for most (no threshold set), or for undefined purple alarms you should see no sub-menus rendered under "Display Alarm Thresholds" menu.
-can try the same for table, but no alarms with thresholds currently active/ack'd
=> Display thresholds

.gitignore, slam/alarm_item.py, slam/alarm_tree_model.py, slam/main_window.py
So far I've only edited main_window.process_message. It's not obvious to me where else I would need to account for protocol prefixes. 
I also am not sure how I can test this, but at the very least I was able to:
- pass all the pytests
- pass the pre-commit jobs
- pass the github workflows
- run the gui with some of the pcds nalms configs which work exactly the same as far as I can tell.
=> Adding support for non-implicit ca protocls
